language: erlang
script: mix test
install: mix deps.get
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - wget -q http://dl.dropbox.com/u/4934685/elixir/v0.9.0.zip && unzip -qq v0.9.0.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
